name: todoapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts:
  sizer: ^2.0.15
  intl: ^0.18.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  build_runner: ^2.1.0
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "images/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

